language: node_js
node_js:
  - "9"
  - "8"
sudo: required 
dist: trusty
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++ libtool autoconf automake
  - npm install -g npm@latest
install: 
  - npm install
script:
  - eslint src *.js